# Generated by Django 2.2.16 on 2020-09-29 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
    ]
