# Generated by Django 2.2.16 on 2020-09-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0002_auto_20200929_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='URL',
        ),
    ]
