# Generated by Django 2.2.16 on 2020-09-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grab', '0004_auto_20200929_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
