# Generated by Django 2.2.16 on 2020-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0008_auto_20200929_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='author_URL',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
