# Generated by Django 2.2.16 on 2020-09-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0009_picture_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='author_URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
